### ISSUE TITLE
Container keeps failing with UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1530: invalid start byte

### ISSUE THREAD

**Issue by bappctl** [Kohimax/qna-api#3]
Tried the example here. The container keeps failing with below error. How to overcome it?

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1530: invalid start byte

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/conda/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/haystack/__init__.py", line 5, in <module>
    from haystack.finder import Finder
  File "/opt/conda/lib/python3.8/site-packages/haystack/finder.py", line 8, in <module>
    from haystack.reader.base import BaseReader
  File "/opt/conda/lib/python3.8/site-packages/haystack/reader/__init__.py", line 1, in <module>
    from haystack.reader.farm import FARMReader
  File "/opt/conda/lib/python3.8/site-packages/haystack/reader/farm.py", line 9, in <module>
    from farm.data_handler.data_silo import DataSilo
  File "/opt/conda/lib/python3.8/site-packages/farm/__init__.py", line 3, in <module>
    import torch.multiprocessing as mp
  File "/opt/conda/lib/python3.8/site-packages/torch/__init__.py", line 500, in <module>
    _C._initExtension(manager_path())
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 119, in <module>
    _lazy_call(_check_capability)
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 117, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
  File "/opt/conda/lib/python3.8/traceback.py", line 197, in format_stack
    return format_list(extract_stack(f, limit=limit))
  File "/opt/conda/lib/python3.8/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/opt/conda/lib/python3.8/traceback.py", line 366, in extract
    f.line
  File "/opt/conda/lib/python3.8/traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/opt/conda/lib/python3.8/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/opt/conda/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/opt/conda/lib/python3.8/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1530: invalid start byte

```

**Comment by bappctl** [comment]
Turned to be editor introduced issue. Closing it.
